### ISSUE TITLE
Client routes created for react-intl

### ISSUE THREAD

**Issue by valse** [universse/gatsby-plugin-now#1]
Hi, I'm using your plugin together with the `gatsby-plugin-intl` one and I notice a fake 404 response when I refresh a page from a language route like the homepage `/en/`.

I saw in the created `__now_routes_g4t5bY.json` json file that these extra rules are added:

```json
{
    "src": "/en/.*",
    "dest": "/en/404/"
},
{
    "src": "/it/.*",
    "dest": "/it/404/"
}
```

from the client side routes generation... causing the above issue.
How can I avoid to add them?

thanks

PS: I can't find how your file `__now_routes_g4t5bY.json` is read by now... is it a naming convention?

**Comment by bardaxx** [comment]
Absolutely, you can get the same kind of issue [here](https://covidlive-it-git-feature-multilang.bardaxx.now.sh/en/)

**Comment by phuoccss** [comment]
Hi there. It would be great if you guys can give me a repo that reproduces the issue.

**Comment by phuoccss** [comment]
Meanwhile, please try `gatsby-plugin-zeit-now@0.3.0-beta.0` and see if it solves the issue.

Also, `__now_routes_g4t5bY.json` is read here https://github.com/zeit/now/blob/master/packages/now-static-build/src/frameworks.ts.
