### ISSUE TITLE
Adding this plugin breaking tawk integration

### ISSUE THREAD

**Issue by vse-volod** [universse/gatsby-plugin-now#2]
After adding this plugin tawk(online support chat) integration is breaking. Widget works in dev mode, local build, but after deploying to Zeit it disappears.

**Comment by phuoccss** [comment]
Hi. Can you give more details? Any error, log, live website, repo I can take a look at?

**Comment by vse-volod** [comment]
Yeah, of course!
[development build with plugin](https://gatsbytemplates-main-cfznnp9tq.now.sh/)
[production build, without](https://gatsbytemplates.io/)
No errors, seems like tawk script is loading, but not running.

**Comment by phuoccss** [comment]
Can I have you plugin config too? You can also try this and see if it works.

```js
{
    resolve: 'gatsby-plugin-zeit-now',
    options: {
      globalHeaders: {
        'referrer-policy': 'strict-origin',
      }
    }
  }
```

**Comment by vse-volod** [comment]
Thanks, it works now!
But I think It would be nice to add this option as default, because without it a lot of other plugins may be broken too.
And, thanks for plugin, by the way!)

**Comment by phuoccss** [comment]
Yep. I will consider for future releases. Thank you.
