### ISSUE TITLE
gatsby-plugin-zeit-now not compatible with Gatsby version 3

### ISSUE THREAD

**Issue by tizpuppi** [universse/gatsby-plugin-now#4]
When building with latest version of Gatsby I see this warning:

```
warn Plugin gatsby-plugin-zeit-now is not compatible with your gatsby version 3.7.1 - It requires gatsby@^2.0.0
```

**Comment by phuoccss** [comment]
Hi. I haven't used Gatsby for a while. I will take some time to fix this over the weekend. Does the plugin work as expected despite the warning?

**Comment by tizpuppi** [comment]
Hi, Thank you for the reply. Yes we didn't notice any issue despite the warning. I suspect is just the peerDependencies version in `package.json` file.

**Comment by phuoccss** [comment]
I have published a new version. Can you give it a try?

**Comment by tizpuppi** [comment]
Tested with the new version and the warning disappeared. Thank you!
